name: "Markdown Finder"
description: "A GitHub Action to find and analyze Markdown files in a repository"
author: "Your Name"

inputs:
  path:
    description: "The path to search for markdown files"
    required: false
    default: "."
  analyzers:
    description: "Comma-separated list of analyzers to run (e.g., links, text)"
    required: false
    default: "links,text"
  output_format:
    description: "The output format for the report (e.g., text, latex)"
    required: false
    default: "text"

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.path }}

branding:
  icon: "book"
  color: "blue"
